### ISSUE TITLE
Testing with no interface

### ISSUE THREAD

**Issue by simPod** [thephpleague/tactician#123]
Hi, how do you approach testing with this bus?

Let's say my service has a bus as a dependency and I want to unit-test it. I'm used to create my own fake implementation instead of using eg. Mockery.

How do you do it here? The command bus doesn't have any interface. Thanks for advice! I guess people here have much more experience than me with this bus and testing code around it :)

**Comment by rosstuck** [comment]
Hi Simon,

Good question! Quick answer because it's a holiday here, if that's okay. :)

Usually, I recommend creating your own interface and wrapping Tactician
with it. This type of "bridge" is a very small amount of work (couple lines
of code) and it buys you a lot of flexibility, rather than coupling to an
interface that might work for us but not for you. It's a good practice for
most libraries you import (say, Flysystem, Guzzle, etc)

Hope that helps! Thanks again for using Tactician and for taking the time
to write tests. :)

**Comment by simPod** [comment]
Good idea! Thanks and enjoy your holiday man ;)
