### ISSUE TITLE
Implement CommandBus against interface

### ISSUE THREAD

**Issue by TiMESPLiNTER** [thephpleague/tactician#140]
In version `2.0-rc1` the `CommandBus` class is marked as `final` but it is not implemented against an interface.

Is there any concrete reason for not implementing the class against an interface? Could we add an interface to implement the class against?

**Comment by snapshotpl** [comment]
My question is: there any reason to not be a final?

**Comment by TiMESPLiNTER** [comment]
Okay, so let's extend the scope of this issue: 

- either remove the `final` from the `CommandBus` class 
- or add an interface to reflect the public API of the `CommandBus` class. 

😉

**Comment by rosstuck** [comment]
Hi @TiMESPLiNTER,

Within the scope of Tactician itself, the class is atomic and has no other possible implementations, so I haven't provided an interface.

For the downstream applications/packages, I recommend folks implement their own command bus interface/class as a bridge to Tactician, rather than typehinting for Tactician throughout their entire app.

Some of the common questions/scenarios folks have are:

- _I want to extend the override or change the behavior of the command bus class_: Sure, just implement it in a new class, you just need to support the Tactician middleware, not the Tactician part.
- _I want to decorate the command class_: I recommend using middleware instead of decorators but if you do want to decorate, use your application's own command bus interface for the decorator.
- _I want to mock the command bus class_: Again, I recommend using your application's command bus interface.

While a final class typically has an interface to exchange the implementation, there are cases where an operation is atomic, stateless and not logically interchangable. Within the scope of Tactician's design/view of the world, the role of the command bus is to run through the middleware and nothing else, hence it meets all three of these criteria. Downstream packages/apps have a different viewpoint naturally, but using a bridge interface is an established best practice, IMHO. :)

I hope that explains both the current situation and my thoughts behind it. Please let me know if either of you have any followup questions, but at this time, I won't likely change the final or add an interface.

Thanks for your input though, I do appreciate you taking the time to ask. :)

**Comment by TiMESPLiNTER** [comment]
Alright. Thanks for clarification @rosstuck. I have currently declared a "bus" interface on my own and decorated the tactician BusCommand in my own BusCommand implementing that interface. It's an acceptable solution for me, especially because you have quite good reasons not to add an interface. 😃
