### ISSUE TITLE
Broken Examples

### ISSUE THREAD

**Issue by flavioheleno** [thephpleague/tactician#143]
[This commit](https://github.com/thephpleague/tactician/commit/aed75b326c56834f9d8b8bbdbf37dbe951e238bd) removed the dev-dep `league/container`, which was used by the examples.

See the evidence below:

```bash
$ php examples/1-beginner-standard-usage.php 
PHP Fatal error:  Uncaught Error: Class "League\Container\Container" not found in /Users/flavio/Documents/open-source/tactician/examples/1-beginner-standard-usage.php:26
Stack trace:
#0 {main}
  thrown in /Users/flavio/Documents/open-source/tactician/examples/1-beginner-standard-usage.php on line 26
```

The solution is to either refactor the examples or add back the dev-dep.

I'm happy to provide a PR fixing this as long as the direction is pointed out.

PS: This only affects the master branch afaik.

**Comment by rosstuck** [comment]
Indeed, definitely broken :) I wanted to update these when I redid the docs, but if you'd like to take a crack at updating them, I'd be super happy to have the help!

I probably just removed the League\Container dep without thinking about it, so just re-adding it as a require-dev dependency would be enough right now.

What I wanted to do though was make an integration test that would execute each example and only pass if they didn't crash, that way the build will fail if (when?) I break one of the examples again.

Does that help enough with direction? If not, please feel free to ask further, my OSS time right now super limited and I'm mostly spending it on updating the Tactician bundle since that and the docs are the only 2.0 release blockers.

**Comment by rosstuck** [comment]
P.S. Would be happy to accept this for Hacktoberfest as well if you like!

**Comment by flavioheleno** [comment]
That's definitely enough direction! I'll work on it later today/tomorrow.

In terms of docs for 2.0, can I be of any help with that?

**Comment by rosstuck** [comment]
Awesome, thank you!

For docs, I need to survey what's there, let me get back to you later this week if that's okay? :)

**Comment by flavioheleno** [comment]
For sure!

**Comment by flavioheleno** [comment]
Hey @rosstuck I've implemented a test that executes each example code.
The test will assert both the exit code and the output to ensure it works as expected.
What do you think?

```php
<?php

declare(strict_types=1);

namespace League\Tactician\Tests;

use PHPUnit\Framework\TestCase;

class ExamplesTest extends TestCase
{

    /**
     * @dataProvider exampleFiles
     */
    public function testExample(string $file, array $expect) : void
    {
        // executes the example script using the php binary
        exec(
            implode(
                ' ',
                [
                    '/usr/bin/env',
                    'php',
                    '-f',
                    escapeshellarg(__DIR__ . "/../examples/{$file}")
                ]
            ),
            $output,
            $exitCode
        );

        $this->assertSame(0, $exitCode);
        $this->assertSame($expect, $output);
    }

    public function exampleFiles() : array
    {
        return [
            [
                '1-beginner-standard-usage.php',
                ['User alice@example.com was registered!']
            ],
            [
                '2-intermediate-create-middleware.php',
                [
                    'LOG: Starting RegisterUser',
                    'User alice@example.com was registered!',
                    'LOG: RegisterUser finished without errors'
                ]
            ],
            [
                '3-intermediate-custom-naming-conventions.php',
                ['See, Tactician now calls the handle method we prefer!']
            ],
            [
                '4-conditional-handlers.php',
                [
                    'Dispatched MyExternalCommand!',
                    'User alice@example.com was registered!'
                ]
            ]
        ];
    }
}
```

**Comment by rosstuck** [comment]
Works for me! I'd say add it to the draft PR and let's get it merged :D

I looked through the docs and think I know what I want to do there, so I'll pick that up soon. I need to split out the 1.x docs and update with the new League templates.

If you'd like to do more in Tactician:

- Not sure if you've got Symfony experience but the Bundle always needs more love and that's not an ecosystem I'm actively involved in anymore.
- Getting the PHP8 tests passing would be great because...
- ...I think support for mapping by MapByAnnotation would be awesome for 2.1. :smile_cat: 

If none of that sounds fun though, don't sweat it, I'm already very appreciative!

**Comment by flavioheleno** [comment]
Awesome! I'll add it to the PR and remove the draft flag.

I have no experience in Symfony, so I think I'm not the best person to give it a shot right now, but I'd love to work on getting PHP 8 support to Tactician!

I will start working on it later today/tomorrow!
