### ISSUE TITLE
InMemoryLocator::addHandlers only allowing new instance of Handler class being stored

### ISSUE THREAD

**Issue by NigelGreenway** [thephpleague/tactician#24]
I was wondering what the implications of storing the mapping of a command to its handler are if this was used on a considerately sized project with many objects being initialised in an array of say 200+ entries like so:

```php
$commandMapping = [
    // ...
    'My\CommandA' => new \My\CommandHandlerA,
    // ...
];
```

Would it be better if tactician allowed for the string of the class fqcn as well as the newly instantiated class? Could this have an effect on memory consumption?

Might be fine and I am worrying about nothing but thought I would ask...

**Comment by rosstuck** [comment]
You're correct in worrying about the performance overhead, so it's a fair question. :)

We could allow the FQCN but that would make the InMemoryLocator more complex. More importantly though, it would start turning the locator into DI container and a poor one at that, since most handlers are going to need dependencies as well. 

Therefore, I'd recommend picking an existing container (Pimple, League/Orno, Symfony's, etc) and implementing a custom HandlerLocator that wraps one of them as an adapter. So:

```php
<?php

class PimpleLocator implements HandlerLocator
{
    private $pimple
    
    private $commandToHandlerIdMap;

    public function __construct(Pimple $pimple) {
        $this->pimple = $pimple;    
    }
    
    public function addHandler($handlerId, $commandClassName)
    {
        $this->commandToHandlerIdMap[$commandClassName] = $handlerId;
    }
    
    public function getHandlerForCommand(Command $command)
    {
        $className = get_class($command);

        if (!isset($this->commandToHandlerIdMap[$className])) {
            throw MissingHandlerException::forCommand($command);
        }
        
        $serviceId = $this->commandToHandlerIdMap[$className];
        return $this->pimple->get($serviceId);
    }
}
```


If you're interested in doing something like this, there's an open issue for a League container here that could use some love.  https://github.com/thephpleague/tactician/issues/9 

Likewise, our goal is to implement a custom locator for ZF2, Symfony and Laravel as we build framework integration for each of those.

Hope that answers your question! :smiley:
