### ISSUE TITLE
Preventing a loop when dealing with external commands

### ISSUE THREAD

**Issue by acairns** [thephpleague/tactician#33]
Regarding: examples/6-conditional-handlers.php

Assuming we are using only one bus for local and remote commands, and the same codebase for our app and workers:

We send `MyExternalCommand` into the bus. Since our Middleware detects an implementation of `ExternalCommand`, we dispatch it to our external service and break the chain.

Life is good.

Our worker servers pop the job from the queue and hydrate our `MyExternalCommand` with the data, ready to be handled - and throw this into our bus... but the command still implements `ExternalCommand`, and it gets re-queued because the bus has the same middleware.

I'm trying to avoid any situation where the client determines if the command requires queueing, such as wrapping it before passed into the bus, or multiple buses. I'm happy to have it wrapped in the bus, but in this example it would still loop.

One option I'm considering is the detection of a worker environment and not including `ExternalCommandMiddleware` within the stack - they are supposed to do the work after all... but this feels... bad.

My code isn't exactly the same as the example, but assume `ExternalCommandMiddleware` gets an instance of `Illuminate\Queue\QueueInterface` passed in, and it's pretty much the same.

Original Twitter Conversation: https://twitter.com/andrewcairns/status/568745541087195136

Related issue: https://github.com/thephpleague/tactician-bernard/issues/11

Pings: @rosstuck, @sagikazarmark (would love your thoughts guys!)

**Comment by sagikazarmark** [comment]
I am generally against the idea of making the `ExternalCommandMiddleware` aware of any detection and limitation logic. I said in the referenced issue that it is not the way it should work. I showed several scenarios (although probably not all of them are in the referenced issue). The point is the same codebase argument is less important IMO than having clean, decent code.

(Honestly, the more I think about this idea, the more I think it is bad....very bad. However I can imagine adding an envelope logic (besides `Bernard\Envelope`) and unwrapping it somewhere so that it can't be requeued. However that should go into a separate setup like `LazyQueueMiddleware`)

**Comment by rosstuck** [comment]
@acairns As suggested in thephpleague/tactician-bernard#11, we could avoid the loop by using a different type of wrapping for the second pass. I know you're using a different queuing system than Bernard, but perhaps we can continue the convo there because I suspect the ultimate solution is always the same and it's easier than chasing across multiple threads :smile:

**Comment by acairns** [comment]
Sure thing!
