### ISSUE TITLE
Laravel Service Provider

### ISSUE THREAD

**Issue by ghost** [thephpleague/tactician#34]
Hi I have created a working service provider for the Laravel 5, if any one interested to refer it as base for creating a better Service Provider you can find the current implementation in https://github.com/rohith-m/tactician

I am not familier with the phpunit testing so no tests are added, directory structure will need rework.

Files:

Service Provider : https://github.com/rohith-m/tactician/blob/master/src/Providers/LaravelServiceProvider.php

Locator : https://github.com/rohith-m/tactician/blob/master/src/Handler/Locator/LaravelLocator.php

Config : https://github.com/rohith-m/tactician/blob/master/src/Config/laravel.php

Hope somebody can use this info and create a better service provider for laravel

**Comment by rosstuck** [comment]
Hi @rohith-m, thanks for sending this in! I'd really like to have better Laravel support and a provider has been the todo list for a while.

If you're interested in turning it into a separate package for Tactician, I'd really appreciate the help and will be glad to offer feedback as you go. Otherwise, this is a great start and kudos for doing it. :)

**Comment by rosstuck** [comment]
For anyone reading this issue in the future, @xtrasmal is working on a similar provider as well https://github.com/xtrasmal/TacticianProvider

@xtrasmal Maybe take a look at the Provider at the root of this issue, there might be some unresolvable differences but could also give you a running head start. :) We'll go further on your repo though.

**Comment by xtrasmal** [comment]
@rosstuck ok will do

**Comment by rizqidjamaluddin** [comment]
For whichever package gets adopted as canonical: please make the locator instance user-configurable and available on Laravel's container. Enforcing a name-transposing naming pattern would be a significant limitation, so users should be allowed to pick what locator they wish to use - and let them interact with it from their own service providers.

I'm also a bit iffy about having users instantiate middleware in configuration details; this isn't really an ideal way to put it, because some users have have cases like some middleware being enabled on certain environments only; with L5's environment detection model, this is very tricky if the middleware stack is just an array sitting in a config file. Laravel makes an example of making middleware stacks and other customizable bits be located in a service provider that's then placed in userland, providing full flexibility (as well as better practice).

I'm not sure of a perfect solution myself, just some thoughts.

**Comment by joselfonseca** [comment]
Hello @rosstuck i really like this command bus and i took some time to write a Laravel implementation, it is a package with the service provider, it resolves the clases from the laravel container and it has tests. I would love some feedback :)

https://github.com/joselfonseca/laravel-tactician 

Thanks!

**Comment by rosstuck** [comment]
@joselfonseca Hey, thanks for the hard work! :smile: 

Looking at the package a bit, it seems almost like you've made a new command bus + interface based on Tactician. It goes pretty far for just integration but that it's cool you were able to put it together like that. Thanks for sharing!

**Comment by rosstuck** [comment]
Also, just a general ping to folks interested before I close this thread, but we're up to something like 6 Laravel integration packages on Packagist. That's a wee bit overkill so I'm going to sit down to do a review in the coming weeks and see about:

- finding out what's missing to keep people from building new ones
- get a longer term maintenance plan in place
- potentially promoting one or two packages to an officially recommended status

This isn't going to happen directly (due to life) but it will be the case going forward.

Thanks to everyone who's contributed thus far!
