### ISSUE TITLE
Chain Of Responsibily best practice?

### ISSUE THREAD

**Issue by Atriedes** [thephpleague/tactician#40]
Hi,

Is there any best practice example about executuning chaining command?

for example I have `UserRegistrationCommand` and `CreateUserGroupCommand` and I want execute `CreateuserGroupCommand` inside `UserRegistrationHandler` how I can do this in best way? right now I do this way below

~~~php
public function handle(Command $command) 
{
	if ($this->groupRepository->isGroupExist($command->getGroupId())) {
		// Shoud I pass command bus in constructor? so I just need execure CreateUserGroupCommand
		$createUserGroupCommand = CreateUserGroupCommand();
		$createUserGroupCommand->setUserRegistrationCommand = $command;
		$this->bus->handle($createUserGroupCommand);
	}
}
~~~

This is have disadvantage, `CreateUserGroupCommand` always depend on `UserRegistrationCommand`

Is there any advice or suggestion?

**Comment by rosstuck** [comment]
Hi @Atriedes,

Thanks for trying out Tactician. :)

Strange as sounds, I don't typically recommend chaining commands like this. To me, a command bus works best when you're using it to pass information from your controller layer to the domain or service layer. So, if we're already inside the Handler with the first command, we've already passed that boundary. There's very little value in going back outside of that boundary to only come back in again. :) 

Based on your question though, I'm guessing there's some code you'd like to reuse here. For example, an end user can send either a RegisterUserCommand or a CreateUserGroup command. If there is duplicate code there (and it's enough to be useful), then I would recommend extracting that to another object altogether and including that object as the dependency with both handlers, rather than the command bus. Here, that could be as simple as a `findOrCreate` on your groupRepository, rather than relying on a whole other command and dispatch cycle.

I know that's not the answer you might've preferred but it's the best advice I have to give. 

I'm going to close this issue because it's not a software bug but if you have any other questions, feel free to comment again or send me an email. :smile:
