### ISSUE TITLE
Silex Service Provider

### ISSUE THREAD

**Issue by Atriedes** [thephpleague/tactician#44]
Hi,

I just create silex service provider here : https://github.com/Atriedes/tactician-service-provider

feedbacks are appreciated!

**Comment by rosstuck** [comment]
Hi @Atriedes, that looks really cool! 

I don't have much experience with Silex myself but I'll give the code a once over in the next few days and offer some general code review points if you're interested. Also, if you're going to maintain it for a while, I'd be willing to link to it from the docs so other folks know it's out there. :)

Thanks again for using Tactician, and feel free to let me know if there's anything you feel we could improve. :)

**Comment by Atriedes** [comment]
Thanks, code review is great too.

Yeah I'll be maintain it. It will useful if other folks have idea to improve tactician in silex

In general, I don't have any suggestion, this library already awesome :)

**Comment by rosstuck** [comment]
I've linked to the service provider from our Installation docs under a new 3rd party section. :)

After looking through the service provider, the only things that jumped out at me were:

- the non-standard EOF ending
- middlewares is already plural so you can just call the config key middleware
- it might be nice to have the command->service id converter be a pluggable strategy.

Otherwise, seems like a solid job. Thanks for contributing, much appreciated! :smile:

**Comment by Atriedes** [comment]
Ah yeah, I will refactor the code as you suggested thanks for point it out
