### ISSUE TITLE
Pimple locator

### ISSUE THREAD

**Issue by ihabunek** [thephpleague/tactician#67]
I created a locator which works with the Pimple DI container:
https://github.com/ihabunek/tactician-pimple

If you create a project for this in the league, or decide to put it in a project with other plugins, I'll be happy to create a pull request on that project.

**Comment by ihabunek** [comment]
Any chance of accepting this? :)

**Comment by rosstuck** [comment]
Sorry for the horrid delay. I've been thinking about this one a bit and for now, I'm going to stop accepting any new Container integrations in favor of the new CallableLocator. 

The container integrations are great but since they inherently have dependencies, I have to split them into separate repos and the overhead of maintaining repos is too high for the benefit gained. Also, some of them are of varying quality or maintainer attention so it'd be better to have one main container.

I'd be happy to add a link to the docs for the PimpleLocator though, if you'd like to keep supporting it though! :)

**Comment by ihabunek** [comment]
Sure, I'd like to support it. Since it's not officially in the league, I'll need to change the namespace. Also add some docs.

**Comment by rosstuck** [comment]
Adding to Community page in a few

**Comment by ihabunek** [comment]
Thanks for the heads up. I should write some docs and make a release.

**Comment by rosstuck** [comment]
That'd be pretty awesome. Thanks again for contributing this, I think a lotta folks will appreciate it. :)

**Comment by ihabunek** [comment]
I have done it finally :)
https://github.com/ihabunek/tactician-pimple
