### ISSUE TITLE
Locking middleware does not work with exceptions

### ISSUE THREAD

**Issue by pkruithof** [thephpleague/tactician#75]
When I'm using the locking middleware, as soon as a handler throws an exception (which can happen in runtime), subsequent commands are not executed due to the `isExecuting` flag being `true`.

I'm not that familiar (yet) with the command bus in practice, but it seems it should catch exceptions, mark as not executing, and rethrow the exception.

This is especially useful when working with workers that sends multiple commands in a row.

**Comment by rosstuck** [comment]
Hmm, sounds about right. I typically just kill the worker when an exception
is raised but depending on your use case, this is valid and we should
support it rather than locking the bus (and probably causing a memory leak)

The only part I'm wondering about is the failure mode. I reckon we should
also toss any commands built up in the in memory queue as well but that
might not always be the desired behavior.

Any thoughts?

**Comment by rosstuck** [comment]
Also, thank you for taking the time to report this issue and I apologize
for any trouble it's caused. :)

**Comment by pkruithof** [comment]
First let me explain why it can be a design decision if you want to handle errors outside of the handler. For instance, say you have a `UpdateArticleCommand`, that can be triggered by a worker (system action), or a controller (user action). In the user's case, I want to handle the exception differently: show a nice error message, etc.

So what happens now is: a command is sent to the bus, somewhere inside the handler an exception is thrown, now the bus is useless: any subsequent commands are queued and there is no way to ever handle them again.

The point is, failure or not, the command has been handled. And since handling a command is a isolated event, especially with this middleware, it should not effect other commands from being handled.

So I think the adjustment should be as minimal as possible, letting the caller decide what to do. Rethrow the exception and let the command bus continue with the next command. If I — like you said — want to bail out and quit the worker, I can do just that. But if my worker handles many different commands, I want it to log the error (requeue the job, etc), and continue with the next.

**Comment by rosstuck** [comment]
Hi Peter, I understand what you're saying and agree. When I mention the in-memory queue, I'm talking about the array one inside the LockingMiddleware, not the remote worker queue (ala Gearman or Beanstalk)

Let's say I have a Command called "Foo" which results in 3 other commands being dispatched (we'll call them A, B and C). Since Foo is being handled when A, B, and C are dispatched, they're kept in an array inside the LockingMiddleware for future handling, then popped off the stack and handled once Foo is complete. ( https://github.com/thephpleague/tactician/blob/master/src/Plugins/LockingMiddleware.php#L21 and https://github.com/thephpleague/tactician/blob/master/src/Plugins/LockingMiddleware.php#L43)

My question is, what happens if Foo and A succeed, but B fails: we still have C in the pending queue. We have a few possible options here: 

- 1) Reset the bus from locked and leave C in the queued array. The next time you dispatch a command, C will run first then your new command. If you never run a new command, C is lost.
- 2) Reset the bus from locked and drop whatever's in the queued array. C never gets run but it's consistent behavior.
- 3) We catch the exception, stuff it into some custom MultiException and dispatch C (and whatever's after it). Once we've exhausted the queued array, we throw our MultiException. This way feels pretty lousy to me since you can't easily see which ones succeeded or failed.

Don't worry, this is a bug and we're going to fix it. I just want to consider the consequences before making a quick change. :smile:

**Comment by pkruithof** [comment]
Interesting case :) I think this too depends on the context: if A/B/C depend on each other (ie: a chain of commands that need to be completed in succession) then you'd want a solution like 2. Otherwise I would prefer number 1.

Either way, I don't think you can enforce a way here that satisfies all possible contexts. So by not implementing a 'solution' at all you let the caller handle it instead. Which is also the exact outcome you would have without the locking middleware (and therefore what I'd expect).

**Comment by rosstuck** [comment]
Hey, just a quick update: I'm planning to pick this up and push out a new release at a hackathon this coming weekend. Sorry for the delaying actually doing it, it's important; I'm just a bit snowed under this month. :smile: 

Regarding the proposed solutions, I agree there's no perfect answer here. I need to sit down and map them all out. At this point I'm leaning toward "dropped the queued" jobs considering that's the most consistent behavior and they're probably relying on the initial job succeeding as well (trickier if it's in a fanned out chain though).

Will update again once a PR is available, thanks for your patience!

**Comment by mikemix** [comment]
Why not make use of the Strategy Pattern and let developers decide which one would be best for them?

**Comment by RonRademaker** [comment]
You could also combine option 1) with a __destruct method making sure any commands left in the queue aren't lost.

**Comment by rosstuck** [comment]
After a long think and some good discussions with a few different folks, I've fixed implement the locking bug and decided to implement the "drop commands on error" route as the default scenario.

Dropping the commands shouldn't effect @pkruithof's scenario since his commands are coming from an external queue and I don't think there's a dependent sequence there (at least, not directly). I apologize for the delay, Peter, and will issue a release later today.

Regarding the dropping of the queued commands (stop reading here if you're not interested):
This isn't a BC break for folks dispatching commands within commands since the locking bug meant they could never recover those in the first place.

As discussed earlier, dropping the queued commands is the easiest scenario to reason about, the easiest to recover from properly, has the least chance of causing future errors due to lingering state and frankly, encourages the better design: I prefer commands that issue events on successful transactions which then trigger commands, rather than commands that directly dispatch commands.

On a final note, we could make this configurable but the LockingMiddleware is recommended as a general purpose scenario. Making it configurable, we pass the burden onto every user, many of whom probably won't understand the full implications of this ("no, don't drop commands!") until it bites them in the rear ("my worker is erroring and gobbling my queued jobs because some earlier, unrelated command failed!")

For those users who really MUST have the non-dropping behavior, I recommend a custom middleware based on the LockingMiddleware. It's almost impossible to cover every scenario out of the box here.

Thanks for the input and patience of everyone involved.
