### ISSUE TITLE
PHP version constraint tigher than required

### ISSUE THREAD

**Issue by RonRademaker** [thephpleague/tactician#81]
Hi,

Your talk at the dutch php conference got me inspired to check out the command bus for our framework. Unfortunately we're stuck at PHP 5.4 at the moment and tactician requires 5.5+. I looked a bit further and I found that the 5.5 requirement is only used in the unit tests (::class syntax).

I changed the tests on my local copy and all test pass just fine in PHP 5.4. Are you interested in the PHP 5.4 testset which would allow a PHP requirement of >=5.4?

Regards,
Ron

**Comment by rosstuck** [comment]
Hey @RonRademaker, thanks for checking it out! (...and for coming to my talk)

I've thought about 5.4 support a couple times but 5.4 is supposedly EOL in September, including no more security updates. Also considering the `::class` syntax is so useful for mapping commands, I'd prefer to keep using it tests/examples/etc.

Finally, we've got a couple more features coming out later this year which may use 5.5 features, like generators. It's all fairly straightforward right now but I'd rather not have to commit to 5.4 support as well, especially with the EOL so close.

So, short answer: probably not. I understand the pain of being stuck on an older version and sympathize. If you really, really can't upgrade, then having seen the talk, you know how easy assembling your own command bus would be, so that may be a valid choice.

I appreciate the effort though and sorry to disappoint!

**Comment by RonRademaker** [comment]
Thanks for the quick reply. I understand your position. We want and need to upgrade soon, so I'll see whether I use a fork or my own bus till that time.

**Comment by rosstuck** [comment]
I think your private fork with the modified tests+a less strict composer.json, combined with a local composer alias (but not on packagist) would be a good solution in the meantime. That would also let you make use of the plugin packages as well, if necessary, and then it's easy to roll forward later. That's probably what I would do, at least. :smile: 

I'll close this issue for now but if you've got any questions, feel free to ping me or leave another comment! Good luck!

**Comment by RonRademaker** [comment]
Hi Ross, 

Thanks, making a fork works for me for now. 

How do you deal with plugins people create? I made one (still very much in development) and if anyone is interested I'd be happy to share (and get feedback to improve the plugin). 

----- Original Message -----

**Comment by rosstuck** [comment]
Most of the plugins with external dependencies (Doctrine, Bernard, etc) are in separate plugin packages. If you've got a plugin and it's not already covered by one of our existing ones, open an issue for it on this repo and we can talk it through; I'd love to see it! 

If you'd prefer to talk in private first, ping me on freenode (rosstuck) or phpnl if you're there :)
