### ISSUE TITLE
Tests missing in releases

### ISSUE THREAD

**Issue by RonRademaker** [thephpleague/tactician#98]
The ```.gitattributes``` file removes the tests from the release, both https://github.com/ConnectHolland/tactician-prioritycommand-plugin and https://github.com/ConnectHolland/tactician-scheduler-plugin use these tests in their own tests. Would you mind including the tests in the releases, or is there some other way to get the tests (and keep them up to date)?

**Comment by rosstuck** [comment]
Hi @RonRademaker! This is by design of the League's definition of quality and is supposed to be this way (please see https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production for reference).

In theory, the tests should be there on your development and CI checkouts, just not in production, so it shouldn't affect your tests. Unless you're running the tests in production on every release, it shouldn't be an issue? If there's some other use case I'm not aware of, please let me know, though the policy decision is a bit above my pay grade. :)

**Comment by RonRademaker** [comment]
Yeah, I understand why they're not in the release, makes a lot of sense. It's just that I depend on the tactician package and it installs the production release in the dev environment, which also makes sense. I just tried around and if I use ```--prefer-source``` with composer the installation includes the tests. I just have to make sure to add that to my docs :)

**Comment by rosstuck** [comment]
Understood, thanks for the update and closing the issue. :+1:
